# -----------------------------------------------------------------------------
# SITE SETTINGS
# -----------------------------------------------------------------------------

title: Turning Point USA at West Virginia University
description: >- 
  The official website for the Turning Point USA chapter at West
  Virginia University.
baseurl: "/tpusawvu-site" # This MUST match your repository name
url: "" # We will set this when we add the custom domain later

# -----------------------------------------------------------------------------
# THEME SETTINGS
# -----------------------------------------------------------------------------

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" 

# -----------------------------------------------------------------------------
# PLUGINS
# -----------------------------------------------------------------------------

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# -----------------------------------------------------------------------------
# SITE AUTHOR & LOGO
# This controls the logo and name at the top.
# -----------------------------------------------------------------------------

author:
  name: "Turning Point USA at West Virginia University"
  avatar: "/West Virginia University.png" # Make sure your logo file is in the root folder!

# -----------------------------------------------------------------------------
# NAVIGATION MENU
# This builds the menu links.
# -----------------------------------------------------------------------------

masthead:
  type: "centered" # Centers your navigation
  nav:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Events"
      url: "/events/"
    - title: "Donate"
      url: "/donate/"
